name: Testing build
on:
  push:
    branches:
      - "main"

  workflow_dispatch:
  repository_dispatch:
    types: [test_input]
    inputs:
      config-file-name:
      description: 'config-fil'
      required: true

jobs:
  create-tag:
    name: Get git tag for commit
    runs-on: ubuntu-latest
    outputs:
      artifact_version: ${{ steps.artifact-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
  build:
    name: Build and push docker image
    needs: create-tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.docker-tag.outputs.image_tag }}
    env:
      ARTIFACT_VERSION: ${{ needs.create-tag.outputs.artifact_version }}
      DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - name: echo input
        run: |
          echo "Input er ${{ github.event.inputs.config-file-name }}"
      - name: Create docker image tags
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ env.ARTIFACT_VERSION }}" >> $GITHUB_ENV
      - name: Output docker image tag
        id: docker-tag
        run: |
          echo "::set-output name=image_tag::${{ env.DOCKER_TAG }}"
      - name: Output environment to deploy to
        id: output-environment
        run: |
          echo "::set-output name=environment::${{ github.event.inputs.environment }}"