name: After build we will deploy
on:
  workflow_run:
    workflows: ["Testing build"]
    branches: [main]
    types:
      - completed
  repository_dispatch:
    types: [deploy_miljo_tag]

jobs:
  deploy:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.
        run: |
          echo "github.event.repository_dispatch: ${{ github.event.repository_dispatch }}"
      - name: Echo GITHUB_SHA
        if: ${{ github.event.repository_dispatch || github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "event_name : ${{ github.event_name }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Output version
        run: |
          echo "Artifact version: ${{ steps.artifact-version.outputs.version }}"