name: After build we will deploy
on:
  workflow_run:
    workflows: ["Testing build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.sha
        run: |
          echo "Github sha: ${{ github.event.inputs.environment }}"
      - name: Echo GITHUB_SHA
        run: |
          echo "env ref: ${{ env.GITHUB_SHA }}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Output version
        run: |
          echo "Artifact version: ${{ steps.artifact-version.outputs.version }}"