name: manuell deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Cluster to deploy to'
        required: true
        default: 'dev-sbs-intern'
      config-file-name:
        description: 'Config file name'
        required: true
        default: 'filnavn'
  repository_dispatch:
    types: [test_input]


jobs:
  deploy:
    name: Deploy from not main
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: |
          echo "CLUSTER=${{ github.event.inputs.environment }}${{ github.event.client_payload.environment }} >> $GITHUB_ENV"
          echo "CONFIG=${{ github.event.inputs.config-file-name }}${{ github.event.client_payload.config-file-name }} >> $GITHUB_ENV"
      - name: echo input
        run: |
          echo "Input er ${{ github.event.inputs.config-file-name }}"
      - name: Deploy til GCP
        run: |
          echo "Github: ${{ github.event }}"
      - uses: actions/checkout@v2
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Output version
        run: |
          echo "Trenger input... ${{ env.CLUSTER }} & ${{ env.CONFIG }}"